### PR TITLE
Added new Search-bar with location 

### PR DESCRIPTION
**Pull request by CbnMarian**
feat: Implement job and location search functionality

- Added an input for job search with dynamic suggestions.
- Implemented city filtering based on user input, displaying options in a dropdown.
- Added a clear button to reset input fields.
- Implemented a mechanism to close the dropdown when the user clicks outside of it.
- Refactored functions to improve clarity and maintainability.

### CODE REVIEW

**Comment by CbnMarian** [comment]
@lalalaurentiu @talidag @CalinCatuta

**Comment by CalinCatuta** [comment]
Trebe implementat la drop-down datele reale din API.

**Comment by lalalaurentiu** [comment]
@CalinCatuta si ce mai astepti ? Endpoint e creat de suggestion

**Comment by CalinCatuta** [comment]
@lalalaurentiu  acuma am fc brench ca sa putem da accept la pull-req asta acolo si sa facem ultimile modificari ca sa putem sa il dam in productie dupa.

**Comment by lalalaurentiu** [comment]
De ce vrei as-i furi munch @CbnMarian ? Poți lucra direct pe pull requestul lui.

**Comment by lalalaurentiu** [comment]
L-ai bulit😂

**Comment by CalinCatuta** [comment]
Tot munca lui e si in brench si pe main :)

**Pull request merged**
