### PR TITLE
Implemented Job Functionality

### PR DESCRIPTION
**Pull request by CbnMarian**

### CODE REVIEW

**Comment by AdelinaMoroaca** [comment]
@CbnMarian before review please update the branch to the latest production code version 
image

**Comment by AdelinaMoroaca** [comment]
@CbnMarian well done but please update this PR to the production version agreement

**Comment by AdelinaMoroaca** [comment]
@CbnMarian  nice work but can you please fix the search bar and "Cauta" button UI?
please check the B and C Figma layout pages:
image

https://www.figma.com/design/SS81SUL5ZnytusulXYwuUG/Pe-Viitor?node-id=1460-27732&node-type=canvas

if this PR stage were in production now, it would look like this:
image
image
image

and no longer meets the UI width, height + other dependencies standards from Figma, which is already in production.

**Comment by CbnMarian** [comment]
added new changes for the search-bar

**Review by AdelinaMoroaca — CHANGES_REQUESTED** [review]
please fix the Search component responsiveness for 768 - 1279px for Landing.jsx
image

**Comment by CbnMarian** [comment]
i fixed the component for responsive design.

 
Screenshot 2024-11-29 201827
 
added the modifications from main.  

need review.

**Comment by AdelinaMoroaca** [comment]
work in progress

**Comment by AdelinaMoroaca** [comment]
PR status : work in progress

**Review by AdelinaMoroaca — APPROVED** [review]

**Pull request merged**
